const editOrderData = {
  order_data: {
    customer_name: "",
    customer_phone: "",
    customer_address: "",
    customer_email: "",
    grand_total: "48,000",
    items: [
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
      {
        title: "SA-BAND-056",
        diamond_quality: "SI-JV",
        metal_size: "2",
        diamond_weight: "0.01",
        metal_weight: "2",
        sub_total: "24,000",
        diamond_charges: "9,500",
        metal_charges: "21,713",
        making_charges: "12,606",
        discount: "4350",
      },
    ],
  },
};

export default editOrderData;
