const ring_size_guide = {
    headers: [
        {title: 'Circumference (mm)',},
        {title: 'Indian Ring Size',},
        {title: 'US/Canada size',},
        {title: 'UK/Australia/New Zealand size',},
    ],
    sizes: [
        {circumference: '41', indian_size: '1', us_canada_size: '1', uk_australia_size: 'B', },
        {circumference: '42', indian_size: '2', us_canada_size: '2', uk_australia_size: 'D', },
        {circumference: '43', indian_size: '3', us_canada_size: '2 1/2', uk_australia_size: 'E', },
        {circumference: '44', indian_size: '4', us_canada_size: '3', uk_australia_size: 'F 1/2', },
        {circumference: '45', indian_size: '5', us_canada_size: '3 1/4', uk_australia_size: 'G', },
        {circumference: '46', indian_size: '6', us_canada_size: '3 3/4', uk_australia_size: 'H', },
        {circumference: '47', indian_size: '7', us_canada_size: '4', uk_australia_size: 'H 1/2', },
        {circumference: '48', indian_size: '8', us_canada_size: '4 1/2', uk_australia_size: 'I 1/2', },
        {circumference: '49', indian_size: '9', us_canada_size: '5', uk_australia_size: 'J 1/2', },
        {circumference: '50', indian_size: '10', us_canada_size: '5 1/2', uk_australia_size: 'K', },
        {circumference: '51', indian_size: '11', us_canada_size: '5 3/4', uk_australia_size: 'L', },
        {circumference: '52', indian_size: '12', us_canada_size: '6', uk_australia_size: 'L 1/2', },
        {circumference: '53', indian_size: '13', us_canada_size: '6 1/2', uk_australia_size: 'M 1/2', },
        {circumference: '54', indian_size: '14', us_canada_size: '7', uk_australia_size: 'N 1/2', },
        {circumference: '55', indian_size: '15', us_canada_size: '7 1/4', uk_australia_size: 'O', },
        {circumference: '56', indian_size: '16', us_canada_size: '7 1/2', uk_australia_size: 'P', },
        {circumference: '57', indian_size: '17', us_canada_size: '8', uk_australia_size: 'P 1/2', },
        {circumference: '58', indian_size: '18', us_canada_size: '8 1/2', uk_australia_size: 'Q 1/2', },
        {circumference: '59', indian_size: '19', us_canada_size: '8 3/4', uk_australia_size: 'R', },
        {circumference: '60', indian_size: '20', us_canada_size: '9', uk_australia_size: 'S', },
        {circumference: '61', indian_size: '21', us_canada_size: '9 1/2', uk_australia_size: 'S 1/2', },
        {circumference: '62', indian_size: '22', us_canada_size: '10', uk_australia_size: 'T 1/2', },
        {circumference: '63', indian_size: '23', us_canada_size: '10 1/4', uk_australia_size: 'U 1/2', },
        {circumference: '64', indian_size: '24', us_canada_size: '10 3/4', uk_australia_size: 'V', },
        {circumference: '65', indian_size: '25', us_canada_size: '11', uk_australia_size: 'W', },
        {circumference: '66', indian_size: '26', us_canada_size: '11 1/2', uk_australia_size: 'W 1/2', },
        {circumference: '67', indian_size: '27', us_canada_size: '12', uk_australia_size: 'X 1/2', },
    ],
};

export default ring_size_guide